export const DELETE_MOVIE = "DELETE_MOVIE";
export const FILTER_MOVIE = "FILTER_MOVIE";
export const REMOVE_FILTER_MOVIE = "REMOVE_FILTER_MOVIE";
export const SET_CHECKBOX_FILTER = "SET_CHECKBOX_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const HANDLE_LIKE = "HANDLE_LIKE";
